# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [5]:
# Create and solve the relevant system of equations
# 29*c + 41*t = 490
# 23*c + 41*t = 448

A = np.array([[29, 41],
             [23, 41]])
print(A)
B = np.array([490, 448]).T
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print(X)

[[29 41]
 [23 41]]
[490 448]
[[ 0.16666667 -0.16666667]
 [-0.09349593  0.11788618]]
[7. 7.]


In [6]:
# Describe your result
#coffee and tea each cost $7 per bag

## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [7]:
# Create and solve the relevant system of equations
# 12c + 3a = 162
# 8c + 3a = 122

A = np.array([[12, 3],
             [8, 3]])
B = np.array([162, 122]).T

A_inv = np.linalg.inv(A)

X = A_inv.dot(B)
print(X)


[10. 14.]


In [8]:
# Describe your result
# children's tickest are $10 and adults are $14

## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [12]:
# Create and solve the relevant system of equations

# t = 2*o
# 0.5*o + 0.75*t + 1.25*c = 5.25
# o + t + c = 7
# substitute for t in the equations so that eq1 will be square
# 0.5*o + 0.75*2*o + 1.25*c = 5.25 = 2*o + 1.25*c = 5.25
# o + 2*o + c = 7 = 3*o + c


A = np.array([[2, 1.25],
             [3, 1]])
print(A)
B = np.array([5.25, 7]).T
print(B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print(X)


[[2.   1.25]
 [3.   1.  ]]
[5.25 7.  ]
[[-0.57142857  0.71428571]
 [ 1.71428571 -1.14285714]]
[2. 1.]


In [ ]:
# Describe your result
# 2 onions, 1 carrot, 4 tomatoes (2 * onions)

## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [13]:
# Create and solve the relevant system of equations
# 1 bedroom rent = x
# 2 bedroom rent = y
# 3 bedroom rent = z
# x + y + z = 1240
# 0.1*x + 0.2*y + 0.3*z = 276
# z = 2*x
# substitute for z in the two equations
# x + y + 2x = 1240 = 3x + y
# 0.1x + 0.2y + 0.3*2x = 276 = 0.7x + 0.2y

A = np.array([[3, 1],
             [0.7, 0.2]])
print(A)
B = np.array([1240, 276]).T
print(B)
X = np.linalg.solve(A, B)
print(X)


[[3.  1. ]
 [0.7 0.2]]
[1240  276]
[280. 400.]


In [ ]:
# Describe your result
# 1 bedroom rent is 280
# 2 bedroom rent is 400
# 3 bedroom rent is 560 (twice the 1 bedroom rent)

**instead of substitution, could have made matrix A square by creating a third row**

**z = 2*x**

**move the vars to the left and add one for y multiplied by zero**

**-2x + 0y + z = 0**

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 